const ADD_PRODUCT = 'ADD_PRODUCT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const EDIT_PRODUCT = 'EDIT_PRODUCT';
const FILTER_PRODUCTS = 'FILTER_PRODUCTS';

export { ADD_PRODUCT, DELETE_PRODUCT, EDIT_PRODUCT, FILTER_PRODUCTS };
